### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by papatistos** [javierarce/hypothesis#1]
Am I right in assuming that this code is obsolete and won't work today? 
Cheers

**Comment by javierarce** [comment]
Good question. Have you tried running the example in the README.me file?

**Comment by papatistos** [comment]
I'm not a developer so I wouldn't really know what to do. I'm just curious how much effort it would take to integrate hypotheis into ruby software like discourse, for example...

**Comment by javierarce** [comment]
Ok. I just checked the example and the gem seems to work fine.
